### ISSUE TITLE
Improving deployment approach

### ISSUE THREAD

**Issue by pimterry** [adamcooke/staytus#19]
This looks excellent, and I'd like to use it. I don't particularly want to have to install Ruby and set up and maintain a MySQL DB just to run my status site though.

Any enthusiasm for automating this away? I'm mostly imagining adding a Dockerfile that wraps that setup up, so anybody with Docker set up can just pull the staytus image, start it, and go. Happy to do the legwork to put that in place, but obviously only if it's something you'd consider merging.

Non-docker approaches would work perfectly well too, if you can think of a simple one, but I'm not aware of anything that would work quite as neatly for this.

**Comment by adamcooke** [comment]
I haven't worked with Docker but I'm certainly open to that idea.

If you have a [Viaduct](http://viaduct.io) account, you can simply deploy Staytus from the app store over there. It only takes a few seconds but gives you everything you need to get up and running. There is a cost though if you want to use all the functionality because Staytus needs to run two processes (one for the web server and one for the background worker used to send emails)

**Comment by pimterry** [comment]
I'd be looking to host it myself I think, since we've already got quite a bit of deployment infrastructure available, so Docker would be better.

I'll take a look at this soon, hopefully sometime this week, and see if I can put something together.

**Comment by adamcooke** [comment]
Great thanks. 

Do remember that it's sometimes useful to host your status site completely separately to the rest of your network so people can still access it when you might be offline.
