### ISSUE TITLE
Verification email only works when forced by Rails

### ISSUE THREAD

**Issue by Simeon-Heinke** [adamcooke/staytus#315]
Hi,

we've installed Staytus in our environment and everything's running fine. However when the user wants to subscribe he doesn't get a verification mail. The message "Thanks - please check your email..." appears but nothing happened. Also there is no entry in one of the log files. 
When we send it via rails like in one of the other issues it works.

s = Subscriber.last
s.send_verification_email

Our smtp server don't need authentication so we've left the username and password field in the environment.yml empty. 

Is there any solution? Do you need more information?

Greetings

**Comment by misterjaytee** [comment]
I'd suggest you comment out the username and password lines rather than just leave them blank:
```
# STAYTUS_SMTP_USERNAME: 
# STAYTUS_SMTP_PASSWORD: 

```

You also need to make sure you restart staytus after updating environment.yml:
`cd /opt/staytus/staytus`
`sudo -u staytus procodile restart`

If you've done that and it still doesn't work, check the web.log, worker.log and production.log for errors (/opt/staytus/staytus/logs).

**Note**: The commands/locations above assume that you installed staytus in /opt/staytus/staytus per the tutorial at https://atech.blog/atech/install-staytus-tutorial.

**Comment by Simeon-Heinke** [comment]
Hi,

after some research i think there is a problem with the procodile.
We configured a Nginx server to use client certificate authentication and HTTPS. Now the procodile restart won't work. The web procfile restart but stopped immediately. 
As seen in the web.log the process has stopped and tried to respawn 5 times. I also tried to restart the supervisor but the web won't start.

any suggestions?
